ToDoAppDjango/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapps.urls'))
]

ToDoAppDjango/todoapps/urls.py
from django.urls import path

from . import views

app_name = 'todoapps'

urlpatterns = [
    path('', views.index, name='index'),
    path('update_task/<int:topic_id>', views.update_task, name='update_task'),
    path('delete_task/<int:topic_id>', views.delete_task, name='delete_task'),
    path('complete_task/<int:topic_id>', views.complete_task, name='complete_task'),
]

ToDoAppDjango/todoapps/models.py
from django.db import models


class Task(models.Model):
    task_name = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.task_name

ToDoAppDjango/todoapps/forms.py
from django import forms

from .models import *


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

ToDoAppDjango/todoapps/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *
from .models import *
# Create your views here.


def index(request):
    tasks = Task.objects.all()

    if request.method != 'POST':
        form = TaskForm()
    else:
        form = TaskForm(data=request.POST)
        if form.is_valid():
            form.save()
            # Refreshes the page
            return redirect('todoapps:index')

    context = {'tasks': tasks, 'form': form}
    return render(request, 'todoapps/index.html', context)


def update_task(request, topic_id):
    task = Task.objects.get(id=topic_id)

    if request.method != 'POST':
        form = TaskForm(instance=task)
    else:
        form = TaskForm(instance=task, data=request.POST)
        if form.is_valid():
            form.save()
        return redirect('todoapps:index')

    context = {'form': form, 'task': task}
    return render(request, 'todoapps/updateTask.html', context)


def delete_task(request, topic_id):
    task = Task.objects.get(id=topic_id)

    if request.method == 'POST':
        task.delete()
        return redirect('todoapps:index')

    context = {'task': task}
    return render(request, 'todoapps/delete_task.html', context)


def complete_task(request, topic_id):
    task = Task.objects.get(id=topic_id)
    task.completed = True
    task.save()
    return redirect('todoapps:index')

ToDoAppDjango/todoapps/templates/todoapps/delete_task.html
<form action="{% url 'todoapps:delete_task' task.id %}" method="POST">
	{% csrf_token %}
	<p>Are you sure you want to delete {{ task }} ?</p>
	<button name="submit">Submit</button>
</form>

ToDoAppDjango/todoapps/templates/todoapps/index.html
<h1>To-Do</h1>
<form action="{% url 'todoapps:index' %}" method='POST'>
	{{ form.task_name }}
	{% csrf_token %}
	<button name="submit">Submit</button>
	
</form>
{% for task in tasks %}
	{% if task.completed %}
		<p> <s> {{ task }} </s> </p>
	{% else %}
		<p> {{ task }} </p>
	{% endif %}
	<a href="{% url 'todoapps:update_task' task.id %}">Edit</a>
	<a href="{% url 'todoapps:delete_task' task.id %}">Delete</a>
	<!-- <form action="{% url 'todoapps:complete_task' task.id %}" method='POST'> -->
		<a href="{% url 'todoapps:complete_task' task.id %}">Complete</a>	
	<!-- </form> -->
{% endfor %}

ToDoAppDjango/todoapps/templates/todoapps/updateTask.html
<form action="{% url 'todoapps:update_task' task.id %}" method="POST">
	{% csrf_token %}
	{{form}}
	<button name="submit">Submit</button>
</form>